#name = input("Enter your name: ")
#result = len(name)
#name = name.capitalize()
#name = name.upper()
#name = name.lower()
# print(f"Hello {name}!")
#res = name.find("N")
#name = name.replace("n", "X")
#print(name)
print(help(str))